config/routes.rb
Rails.application.routes.draw do
  draw(:hotwire_native)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    unlocks: "users/unlocks",
    confirmations: "users/confirmations"
  }
  resources :sipario_sessions, only: [ :create ]

  devise_for :owners, controllers: {
    registrations: "owners/registrations",
    sessions: "owners/sessions",
    passwords: "owners/passwords",
    unlocks: "owners/unlocks",
    confirmations: "owners/confirmations"
  }

  resources :certified_presences, only: [ :create ]

  # Defines the root path route ("/")
  root to: "home#index"

  get "download_android" => "home#download_android"
  get "download_apple" => "home#download_apple"

  resources :point_events, only: [ :index ] do
    get :consume_code
  end

  resources :providers do
    resources :awards do
      get :redeem
      get :consume
    end

    collection do
      get :search
    end
  end
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :owners
  has_many :awards
  has_many :point_events

  validates :name, :lonlat, :minutes_for_points, presence: true
end

app/controllers/providers_controller.rb
class ProvidersController < BaseUserController
  def index
    @providers = Provider.page(params[:page])
  end

  def show
    @provider = Provider.find(params[:id])
  end

  def search
    lon = params[:lon]
    lat = params[:lat]
    radius = params[:radius] ||= 200 # meters

    if lon.blank? && lat.blank?
      return render json: { error: "missing lat lon" }
    end

    @providers = Provider.where(
      "ST_DWithin(
        lonlat::geography,
        ST_SetSRID(ST_MakePoint(?, ?), 4326)::geography,
        ?
      )",
      lon,
      lat,
      radius
    )
  end
end

app/views/providers/index.html.erb
<h2><%= I18n.t('providers.header') %></h2>

<%= paginate @providers %>

<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= I18n.t('activerecord.attributes.providers.name') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.providers.lonlat') %></th>
      <th scope="col"><%= I18n.t('providers.my_points') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.providers.minutes_for_points') %></th>
    </tr>
  </thead>
  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= link_to provider.name, provider_url(provider) %></td>
        <td><%= provider.lonlat %></td>
        <td><%= current_user.points_for_provider(provider) %></td>
        <td><%= provider.minutes_for_points %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/providers/show.html.erb
<h2><%= @provider.name %></h2>
<h3><%= I18n.t('providers.my_points') %>: <%= current_user.points_for_provider(@provider) %></h3>

<h3><%= I18n.t('awards.header') %></h3>

<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= I18n.t('activerecord.attributes.awards.name') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.awards.description') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.awards.points_to_redeem') %></th>
      <th scope="col"><%= I18n.t('actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @provider.awards.each do |award| %>
      <tr>
        <td><%= award.name %></td>
        <td><%= award.description %></td>
        <td><%= award.points_to_redeem %></td>
        <td>
          <%= link_to provider_award_redeem_path(@provider, award), class: 'text-decoration-none' do %>
            <%= image_tag "cash.svg", aria: { hidden: true }, size: 24 %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>