config/routes.rb
Rails.application.routes.draw do
  draw(:hotwire_native)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    unlocks: "users/unlocks",
    confirmations: "users/confirmations"
  }
  resources :sipario_sessions, only: [ :create ]

  devise_for :owners, controllers: {
    registrations: "owners/registrations",
    sessions: "owners/sessions",
    passwords: "owners/passwords",
    unlocks: "owners/unlocks",
    confirmations: "owners/confirmations"
  }

  resources :certified_presences, only: [ :create ]

  # Defines the root path route ("/")
  root to: "home#index"

  get "download_android" => "home#download_android"
  get "download_apple" => "home#download_apple"

  resources :point_events, only: [ :index ] do
    get :consume_code
  end

  resources :providers do
    resources :awards do
      get :redeem
      get :consume
    end

    collection do
      get :search
    end
  end
end

app/models/point_event.rb
class PointEvent < ApplicationRecord
  belongs_to :provider
  belongs_to :user

  belongs_to :sipario_session, optional: true
  belongs_to :award, optional: true

  validates :points, presence: true
end

app/controllers/point_events_controller.rb
class PointEventsController < BaseUserController
  def index
    @point_events = current_user.point_events.order(created_at: :desc).page(params[:page])
  end

  def consume_code
    @point_event = current_user.point_events.find(params[:point_event_id])
  end
end

app/views/point_events/_point_event.html.erb
<div id="<%= dom_id point_event %>">
  <p>
    <strong>Provider:</strong>
    <%= point_event.provider.name %>
  </p>
  <p>
    <strong>Points:</strong>
    <%= point_event.points %>
  </p>
</div>

app/views/point_events/consume_code.html.erb
<h2><%= I18n.t('point_events.header') %></h2>

<h2><%= @point_event.provider.name %></h2>

<h2><%= @point_event.award.name %> | <%= @point_event.award.description %></h2>

<%= raw(RQRCode::QRCode.new(
      provider_award_consume_url(
        provider_id: @point_event.provider, 
        award_id: @point_event.award,
        award_consume_code: @point_event.consume_code
      )
    ).as_svg.html_safe) %>

app/views/point_events/index.html.erb
<h2><%= I18n.t('point_events.header') %></h2>

<h3><%= I18n.t('point_events.total_points') %> <%= current_user.total_points %></h3>

<%= paginate @point_events %>

<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= I18n.t('activerecord.attributes.point_events.provider') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.point_events.award') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.point_events.points') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.point_events.created_at') %></th>
      <th scope="col"><%= I18n.t('actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @point_events.each do |point_event| %>
      <tr>
        <td><%= link_to point_event.provider.name, provider_path(point_event.provider) %></td>
        <td><%= point_event.award&.name %></td>
        <td><%= point_event.points %></td>
        <td><%= point_event.created_at %></td>
        <td>
          <% if point_event.award.present? && !point_event.used %>
            <%= link_to point_event_consume_code_path(point_event), class: 'text-decoration-none' do %>
              <%= image_tag "qr.svg", aria: { hidden: true }, size: 24 %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>