config/routes.rb
Rails.application.routes.draw do
  draw(:hotwire_native)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    unlocks: "users/unlocks",
    confirmations: "users/confirmations"
  }
  resources :sipario_sessions, only: [ :create ]

  devise_for :owners, controllers: {
    registrations: "owners/registrations",
    sessions: "owners/sessions",
    passwords: "owners/passwords",
    unlocks: "owners/unlocks",
    confirmations: "owners/confirmations"
  }

  resources :certified_presences, only: [ :create ]

  # Defines the root path route ("/")
  root to: "home#index"

  get "download_android" => "home#download_android"
  get "download_apple" => "home#download_apple"

  resources :point_events, only: [ :index ] do
    get :consume_code
  end

  resources :providers do
    resources :awards do
      get :redeem
      get :consume
    end

    collection do
      get :search
    end
  end
end

app/models/award.rb
class Award < ApplicationRecord
  belongs_to :provider

  validates :name, :description, :points_to_redeem, presence: true
end

app/controllers/awards_controller.rb
# frozen_string_literal: true

class AwardsController < BaseOwnerController
  skip_before_action :authenticate_owner!, only: [ :redeem ]
  skip_before_action :set_provider, only: [ :redeem ]

  before_action :authenticate_user!, only: [ :redeem ]

  def index
    @awards = @provider.awards.page(params[:page])
  end

  def new
    @award = @provider.awards.new
  end

  def show
    @award = @provider.awards.find(params[:id])
  end

  def edit
    @award = @provider.awards.find(params[:id])
  end

  def create
    @award = @provider.awards.build(award_params)

    if @award.save
      redirect_to provider_awards_url(@provider), flash: { notice: I18n.t("awards.created") }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @award = @provider.awards.find(params[:id])

    if @award.update(award_params)
      redirect_to provider_awards_url(@provider), flash: { notice: I18n.t("awards.updated") }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @award = @provider.awards.find(params[:id])
    @award.destroy

    redirect_to provider_awards_url(@provider), flash: { success: I18n.t("awards.destroyed") }
  end

  def consume
    @point_event = @provider.point_events.where(consume_code: params[:award_consume_code]).first

    if @point_event.present? && !@point_event.used
      @point_event.update(used: true)

      head :ok
    else
      head :unprocessable_entity
    end
  end

  def redeem
    award = Award.find(params[:award_id])

    if current_user.points_for_provider(award.provider) < award.points_to_redeem
      return redirect_to provider_url(award.provider), flash: { notice: I18n.t("awards.too_few_points") }
    end

    current_user.redeem_award(award)

    redirect_to point_events_url, flash: { success: I18n.t("awards.redeemed") }
  end

  private

  def award_params
    params.require(:award).permit(:name, :description, :points_to_redeem)
  end
end

app/views/awards/_form.html.erb
<%= simple_form_for [@provider, award] do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :points_to_redeem, as: :integer %>
  <%= f.button :submit, 'Salva Premio' %>
<% end %>

app/views/awards/edit.html.erb
<%= render "form", award: @award%>

app/views/awards/index.html.erb
<h2><%= I18n.t('awards.header') %></h2>
<div class="row">
  <ul class="nav justify-content-end">
    <li>
      <%= link_to I18n.t('awards.new'), new_provider_award_path(@provider), class: 'btn btn-primary' %>
    </li>
  </ul>
</div>
<%= paginate @awards %>
<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= I18n.t('activerecord.attributes.awards.name') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.awards.description') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.awards.points_to_redeem') %></th>
      <th scope="col"><%= I18n.t('actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @awards.each do |award| %>
      <tr>
        <td><%= link_to award.name, provider_award_path(@provider, award) %></td>
        <td><%= truncate(award.description, length: 25) %></td>
        <td><%= award.points_to_redeem %></td>
        <td>
          <%= link_to edit_provider_award_path(@provider, award), class: 'text-decoration-none' do %>
            <%= image_tag "edit.svg", aria: { hidden: true }, size: 24 %>
          <% end %>
          <%= link_to provider_awards_path(@provider), data: { turbo_method: :delete, turbo_confirm: I18n.t('awards.confirm_destroy')}, class: 'text-decoration-none' do %>
            <%= image_tag "trash.svg", aria: { hidden: true }, size: 24 %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/awards/new.html.erb
<%= render "form", award: @award %>

app/views/awards/show.html.erb
<div class="text-center">
  <h2><%= I18n.t('activerecord.attributes.awards.name') %> | <%= @award.name %></h2>
  <h2><%= I18n.t('activerecord.attributes.awards.description') %> | <%= @award.description %></h2>
  <h2><%= I18n.t('activerecord.attributes.awards.points_to_redeem') %> | <%= @award.points_to_redeem %></h2>
</div>