config/routes.rb
Rails.application.routes.draw do
  draw(:hotwire_native)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    unlocks: "users/unlocks",
    confirmations: "users/confirmations"
  }
  resources :sipario_sessions, only: [ :create ]

  devise_for :owners, controllers: {
    registrations: "owners/registrations",
    sessions: "owners/sessions",
    passwords: "owners/passwords",
    unlocks: "owners/unlocks",
    confirmations: "owners/confirmations"
  }

  resources :certified_presences, only: [ :create ]

  # Defines the root path route ("/")
  root to: "home#index"

  get "download_android" => "home#download_android"
  get "download_apple" => "home#download_apple"

  resources :point_events, only: [ :index ] do
    get :consume_code
  end

  resources :providers do
    resources :awards do
      get :redeem
      get :consume
    end

    collection do
      get :search
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviceFormat
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  around_action :switch_locale

  respond_to :html, :json

  protect_from_forgery unless: -> { request.format.json? }

  def switch_locale(&action)
    locale = extract_locale_from_accept_language_header
    locale = I18n.default_locale unless ACCEPTED_LANGUAGES.include?(locale)

    I18n.with_locale(locale, &action)
  end

  private
    ACCEPTED_LANGUAGES = [ "it", "en" ]

    def extract_locale_from_accept_language_header
      request.env["HTTP_ACCEPT_LANGUAGE"].scan(/^[a-z]{2}/).first if request.env["HTTP_ACCEPT_LANGUAGE"]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.erb
<div id="flash" class="flash">
  <% flash.each do |type, body| %>
    <%
    flash_class = case type
                  when 'notice'
                    'primary'
                  when 'alert'
                    'danger'
                  else
                    'dark'
                  end
    %>
    <%= content_tag :div, class: "alert alert-#{flash_class}" do %>
      <p><%= body %></p>
    <% end %>
  <% end %>
</div>

app/views/application/_footer.html.erb
<div class="container-fluid">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-4 d-flex align-items-center">
      <a href="https://github.com/baldarn/sipario">
        <%= image_tag "github.svg", aria: { hidden: true }, size: 45, class: "bi d-block mx-auto mb-1" %>
      </a>
      <% if ENV['APP_VERSION'].present? %>
        <span class="ms-1">v<%= ENV['APP_VERSION'] %></span>
      <% end %>
      <a href="download_android">
        <%= image_tag "android.svg", aria: { hidden: true }, size: 45, class: "bi d-block mx-auto mb-1" %>
      </a>
    </div>
    <div class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <a href="https://www.iubenda.com/privacy-policy/83684936" class="iubenda-white iubenda-noiframe iubenda-embed iubenda-noiframe " title="Privacy Policy ">Privacy Policy</a><script type="text/javascript">
        (function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);
      </script>
      <a href="https://www.iubenda.com/privacy-policy/83684936/cookie-policy" class="iubenda-white iubenda-noiframe iubenda-embed iubenda-noiframe " title="Cookie Policy ">Cookie Policy</a><script type="text/javascript">
        (function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);
      </script>
    </div>
  </footer>
</div>

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_url %>">
      <%= image_tag "logo.png", aria: { hidden: true }, height: 70, class: "bi d-block mx-auto mb-1" %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
        <% if owner_signed_in? %>
          <li class="nav-item">
            <a href="<%= provider_awards_url(@provider) %>" class="nav-link text-secondary">
              <%= image_tag "gift.svg", aria: { hidden: true }, size: 24, class: "bi d-block mx-auto mb-1" %>
              <%= I18n.t('awards.header' )%>
            </a>
          </li>
          <li class="nav-item">
            <a href="<%= edit_owner_registration_url %>" class="nav-link text-secondary">
              <%= image_tag "profile.svg", aria: { hidden: true }, size: 24, class: "bi d-block mx-auto mb-1" %>
              <%= I18n.t('profile' )%>
            </a>
          </li>
          <li class="nav-item">
            <a href="<%= destroy_owner_session_url %>" class="nav-link text-secondary" data-turbo="false">
              <%= image_tag "door.svg", aria: { hidden: true }, size: 24, class: "bi d-block mx-auto mb-1" %>
              <%= I18n.t('sign_out' )%>
            </a>
          </li>

        <% elsif user_signed_in? %>
          <li class="nav-item">
            <a href="<%= point_events_url %>" class="nav-link text-secondary">
              <%= image_tag "gift.svg", aria: { hidden: true }, size: 24, class: "bi d-block mx-auto mb-1" %>
              <%= I18n.t('point_events.header' )%>
            </a>
          </li>
          <li class="nav-item">
            <a href="<%= providers_url %>" class="nav-link text-secondary">
              <%= image_tag "building.svg", aria: { hidden: true }, size: 24, class: "bi d-block mx-auto mb-1" %>
              <%= I18n.t('providers.header' )%>
            </a>
          </li>
          <li class="nav-item">
            <a href="<%= edit_user_registration_url %>" class="nav-link text-secondary">
              <%= image_tag "profile.svg", aria: { hidden: true }, size: 24, class: "bi d-block mx-auto mb-1" %>
              <%= I18n.t('profile' )%>
            </a>
          </li>
          <li class="nav-item">
            <a href="<%= destroy_user_session_url %>" class="nav-link text-secondary" data-turbo="false">
              <%= image_tag "door.svg", aria: { hidden: true }, size: 24, class: "bi d-block mx-auto mb-1" %>
              <%= I18n.t('sign_out' )%>
            </a>
          </li>
        <% else %>
          <li class="nav-item">
            <a href="<%= user_session_url %>" class="nav-link text-secondary">
              <%= image_tag "unlock.svg", aria: { hidden: true }, size: 24, class: "bi d-block mx-auto mb-1" %>
              <%= I18n.t('log_in_user' )%>
            </a>
          </li>
          <li class="nav-item">
            <a href="<%= new_user_registration_url %>" class="nav-link text-secondary">
              <%= image_tag "door.svg", aria: { hidden: true }, size: 24, class: "bi d-block mx-auto mb-1" %>
              <%= I18n.t('sign_up_user' )%>
            </a>
          </li>

          <li class="nav-item">
            <a href="<%= owner_session_url %>" class="nav-link text-secondary">
              <%= image_tag "unlock.svg", aria: { hidden: true }, size: 24, class: "bi d-block mx-auto mb-1" %>
              <%= I18n.t('log_in_owner' )%>
            </a>
          </li>
          <li class="nav-item">
            <a href="<%= new_owner_registration_url %>" class="nav-link text-secondary">
              <%= image_tag "door.svg", aria: { hidden: true }, size: 24, class: "bi d-block mx-auto mb-1" %>
              <%= I18n.t('sign_up_owner' )%>
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>